name = "MatrixFunctionDiff"
uuid = "5a80cb59-5c4a-4b04-8570-513e0deda534"
authors = ["xquan818 <xuequan818@gmail.com>"]
version = "1.0.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DividedDifferences = "ca54fc82-bf42-49fd-94f8-048f44d9e20a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PermutationSymmetricTensors = "22e17884-8c1a-4ea8-8b39-5974e24a9d31"

[compat]
Combinatorics = "1"
DividedDifferences = "1"
PermutationSymmetricTensors = "0.2"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
